import assert from 'node:assert/strict';
import { api, priceRows, request } from '../src/services/api.js';
globalThis.window = new EventTarget();
let events = 0;
window.addEventListener('bazerlens-data', () => events++);
const calls = [];
const user = { id:'u1', name:'User', role:'user', status:'Active', thana:'Mirpur', city:'Dhaka' };
let next = null;
globalThis.fetch = async (url, options) => {
  calls.push({url,...options,body:options.body && JSON.parse(options.body)});
  return new Response(JSON.stringify(next), { status:200 });
};
next = {user};
assert.equal((await api.login({email:'user@example.com',password:'secret',remember:true})).area,'Mirpur');
assert.equal(calls.at(-1).url,'/api/Auth/login');
assert.equal(calls.at(-1).credentials,'include');
assert.equal(events,1);
next = [];
await api.listSubmissions();
assert.equal(calls.at(-1).url,'/api/Submission/user/u1');
await api.saveSubmission({productId:'p1',marketId:'m1',price:'32.50',date:'2026-09-29',unit:'kg',quality:'Standard',evidenceUrl:'https://example.com/photo'});
assert.equal(calls.at(-1).method,'POST');
assert.equal(calls.at(-1).body.observedOn,'2026-09-29');
assert.equal(calls.at(-1).body.price,32.5);
await api.saveSubmission({id:'s1',price:'30',date:'2026-09-29'});
assert.equal(calls.at(-1).url,'/api/Submission/s1');
assert.equal(calls.at(-1).method,'PUT');
await api.reviewSubmission({id:'s1',status:'rejected',reason:'Check receipt'});
assert.deepEqual(calls.at(-1).body,{status:'rejected',rejectionReason:'Check receipt'});
await api.changePassword({currentPassword:'old',password:'newpass123',confirmPassword:'newpass123'});
assert.equal(calls.at(-1).body.newPassword,'newpass123');
await assert.rejects(api.changePassword({password:'a',confirmPassword:'b'}),/match/);
await api.saveAlert({productId:'p1',targetPrice:'20',enabled:false});
assert.equal(calls.at(-1).body.targetPrice,20);
assert.equal(calls.at(-1).body.enabled,false);
const sample={productId:'p1',marketId:'m1',unit:'kg',product:'Rice',date:'2026-09-29'};
const rows=priceRows([{...sample,price:30},{...sample,price:50},{...sample,date:'2026-09-28',price:100}]);
assert.equal(rows[0].average,40);
assert.equal(rows[0].lowest,30);
assert.equal(priceRows([{...sample,price:30}],{marketId:'m2'}).length,0);
globalThis.fetch=async()=>new Response(JSON.stringify({errors:{Price:['Price must be positive.']}}),{status:400});
await assert.rejects(request('/Submission'),/Price must be positive/);
globalThis.fetch=async()=>new Response('<html>wrong proxy</html>',{status:200});
await assert.rejects(request('/Submission'),/base URL and proxy/);
globalThis.fetch=async()=>{throw new Error('offline');};
await assert.rejects(request('/Submission'),/Cannot reach/);
console.log('PASS: API routes, payload conversion, session credentials, mutation events, price aggregation and errors.');
