import assert from 'node:assert/strict';
import { mockApi as api } from '../src/services/mockApi.js';
import { DB_KEY } from '../src/utils/storage.js';
class MemoryStorage {
  values = new Map();
  getItem(key) { return this.values.get(key) ?? null; }
  setItem(key,value) { this.values.set(key,String(value)); }
  removeItem(key) { this.values.delete(key); }
  clear() { this.values.clear(); }
}
globalThis.localStorage = new MemoryStorage();
globalThis.sessionStorage = new MemoryStorage();
globalThis.window = new EventTarget();
const realTimer = globalThis.setTimeout;
globalThis.setTimeout = (fn) => realTimer(fn,0);
let checks = 0;
const ok = (condition,message) => { assert.ok(condition,message); checks++; };
const rejects = async (fn,pattern) => { await assert.rejects(fn,pattern); checks++; };
const userLogin = () => api.login({email:'user@bazarlens.com',password:'User@123',remember:false});
const adminLogin = () => api.login({email:'admin@bazarlens.com',password:'Admin@123',remember:true});
ok(await api.getSession() === null,'Initially signed out');
await rejects(() => api.listProducts(),/sign in/);
await rejects(() => api.login({email:'bad',password:'x'}),/valid email/);
await rejects(() => api.login({email:'user@bazarlens.com',password:'bad'}),/Invalid email or password/);
await userLogin();
ok((await api.getSession()).role === 'user','User session restored');
ok(sessionStorage.getItem('bazerlens_session_v1') && !localStorage.getItem('bazerlens_session_v1'),'Session-only login');
await rejects(() => api.listUsers(),/Administrator/);
await rejects(() => api.exportDatabase(),/Administrator/);
const products = await api.listProducts(), markets = await api.listMarkets();
ok(products.length === 8 && markets.length === 7,'Seed catalog');
const input = {productId:'p0',marketId:'m1',unit:'kg',price:81,date:new Date().toLocaleDateString('en-CA'),note:'integration test',evidenceUrl:'https://example.com/evidence'};
let submission = await api.saveSubmission(input);
ok(submission.area === 'Dhanmondi' && submission.status === 'pending','Submission created');
submission = await api.saveSubmission({...submission,price:82});
ok((await api.listSubmissions()).find(s => s.id === submission.id).price === 82,'Submission update persists');
ok(JSON.parse(localStorage.getItem(DB_KEY)).submissions.some(s => s.id === submission.id),'Persistence stored');
await rejects(() => api.saveSubmission({...input,price:-1}),/Price/);
await rejects(() => api.saveSubmission({...input,date:'2026-02-30'}),/valid date/);
await rejects(() => api.saveSubmission({...input,unit:'dozen'}),/default unit/);
await rejects(() => api.saveSubmission({...input,evidenceUrl:'javascript:alert(1)'}),/HTTP/);
const temporary = await api.saveSubmission(input); await api.deleteSubmission(temporary.id);
ok(!(await api.listSubmissions()).some(s => s.id === temporary.id),'Pending delete');
let alert = await api.saveAlert({productId:'p0',area:'Dhanmondi',direction:'above',targetPrice:1,enabled:true});
ok((await api.getNotifications()).length > 0,'Matching alert notification');
alert = await api.saveAlert({...alert,targetPrice:2,enabled:false});
ok(!(await api.listAlerts()).find(a => a.id === alert.id).enabled,'Toggle alert');
await api.deleteAlert(alert.id);
ok(!(await api.listAlerts()).some(a => a.id === alert.id),'Alert deleted');
await api.saveSettings({defaultArea:'Dhanmondi',emailAlerts:true,inAppNotifications:false,compactTables:true});
ok((await api.getSettings()).compactTables && (await api.getNotifications()).length === 0,'Preferences and notification effect');
await api.resetSettings();
ok((await api.getSettings()).inAppNotifications,'Reset preferences');
await api.updateProfile({name:'Updated User',email:'user@bazarlens.com',city:'Dhaka',area:'Dhanmondi',avatarUrl:''});
ok((await api.getSession()).name === 'Updated User','Profile updates session');
await rejects(() => api.changePassword({currentPassword:'bad',password:'Changed@123',confirmPassword:'Changed@123'}),/Current password/);
await api.changePassword({currentPassword:'User@123',password:'Changed@123',confirmPassword:'Changed@123'});
await api.logout(); ok(await api.getSession() === null,'Logout');
await api.login({email:'user@bazarlens.com',password:'Changed@123'});
await api.changePassword({currentPassword:'Changed@123',password:'User@123',confirmPassword:'User@123'});
await api.logout();
const signup = {name:'New Contributor',email:'new@example.com',city:'Dhaka',area:'Mirpur',password:'New@1234',confirmPassword:'New@1234',agreeTerms:true};
const newUser = await api.signup({...signup,role:'admin',status:'blocked'});
ok(newUser.role === 'user' && newUser.status === 'active','Signup forces user role');
await rejects(() => api.signup(signup),/already exists/);
await api.login({email:signup.email,password:signup.password});
ok((await api.getSession()).id === newUser.id,'New account login after storage restore');
await rejects(() => api.saveSubmission({...submission,price:90}),/own pending/);
await api.forgotPassword({email:signup.email});
await api.resetPassword({email:signup.email,password:'Reset@123',confirmPassword:'Reset@123'});
await api.logout(); await api.login({email:signup.email,password:'Reset@123'});
ok((await api.getSession()).id === newUser.id,'Demo reset password');
await adminLogin();
ok(localStorage.getItem('bazerlens_session_v1') && !sessionStorage.getItem('bazerlens_session_v1'),'Remembered session');
const admin = (await api.listUsers()).find(u => u.id === 'admin-demo');
await rejects(() => api.deleteUser(admin.id),/yourself/);
await rejects(() => api.saveUser({...admin,status:'blocked'}),/yourself/);
await rejects(() => api.saveUser({...admin,role:'user'}),/one active administrator/);
await api.saveUser({...newUser,status:'blocked'});
await rejects(() => api.login({email:signup.email,password:'Reset@123'}),/blocked/);
await api.saveUser({...newUser,status:'active'});
const extra = await api.saveUser({name:'Temporary',email:'temp@example.com',city:'Dhaka',area:'Mirpur',password:'Temp@123',role:'user',status:'active'});
await api.deleteUser(extra.id);
ok(!(await api.listUsers()).some(u => u.id === extra.id),'User CRUD');
await rejects(() => api.deleteUser('user-demo'),/history/);
await rejects(() => api.deleteProduct('p0'),/referenced/);
await rejects(() => api.deleteMarket('m0'),/submissions/);
let product = await api.saveProduct({name:'Test lentil',category:'Grains',unit:'kg',active:true});
product = await api.saveProduct({...product,active:false}); ok(!product.active,'Product deactivation'); await api.deleteProduct(product.id);
let market = await api.saveMarket({name:'Test market',area:'Test area',district:'Dhaka',division:'Dhaka',active:true});
market = await api.saveMarket({...market,active:false}); ok(!market.active,'Market deactivation'); await api.deleteMarket(market.id);
await rejects(() => api.reviewSubmission({id:submission.id,status:'rejected',reason:''}),/Rejection reason/);
await api.reviewSubmission({id:submission.id,status:'verified'});
await rejects(() => api.reviewSubmission({id:submission.id,status:'rejected',reason:'Second review'}),/already been reviewed/);
ok((await api.getPrices({productId:'p0',marketId:'m1'}))[0].history.some(s => s.id === submission.id),'Approval reaches prices');
await userLogin();
await rejects(() => api.saveSubmission({...submission,price:90}),/pending/);
await rejects(() => api.deleteSubmission(submission.id),/pending/);
const rejected = await api.saveSubmission(input); await adminLogin();
await api.reviewSubmission({id:rejected.id,status:'rejected',reason:'Evidence needs clarification'});
await userLogin();
ok((await api.listSubmissions()).find(s => s.id === rejected.id).rejectionReason === 'Evidence needs clarification','Review reason reaches user');
const analytics = await api.getAnalytics(); ok(analytics.rejected.some(s => s.id === rejected.id),'Review reaches analytics');
ok((await api.getPrices({search:'not a real product'})).length === 0,'Empty prices');
ok((await api.getTrends({productId:'p0',area:'unknown'})).length === 0,'Empty trends');
await api.logout();
const publicData = await api.getPublicStatistics({productId:'p0',area:'Dhanmondi'});
ok(publicData.prices.length > 0 && publicData.trend.length > 0,'Anonymous public statistics and trends');
ok(publicData.prices.every(p => p.productId === 'p0' && p.area === 'Dhanmondi'),'Public filters');
ok(!JSON.stringify(publicData).includes('evidenceUrl') && !JSON.stringify(publicData).includes('userId') && !JSON.stringify(publicData).includes('user-demo'),'Public response contains no private contributor metadata');
await rejects(() => api.listSubmissions(),/sign in/);
await adminLogin();
await api.saveUser({...newUser,role:'agent'});
await api.login({email:signup.email,password:'Reset@123'});
ok((await api.getSession()).role === 'agent','Admin assigns agent role');
await rejects(() => api.listUsers(),/Administrator/);
const normal = await api.saveSubmission({...input,price:66});
ok(normal.status === 'verified' && normal.screening.decision === 'auto-approved' && !normal.flagged,'Normal agent price is automatically approved');
ok(normal.history[0].source === 'automatic' && normal.history[0].reviewerId === null,'Automatic approval has honest audit source');
await rejects(() => api.deleteSubmission(normal.id),/pending/);
await rejects(() => api.saveSubmission({...normal,price:67}),/pending/);
ok((await api.getPublicStatistics({productId:'p0',area:'Dhanmondi'})).prices.some(p => p.date === normal.date),'Automatic approvals reach public statistics');
let unusual = await api.saveSubmission({...input,price:200});
ok(unusual.status === 'pending' && unusual.flagged && unusual.screening.decision === 'unusual','Unusual agent price flagged');
ok(unusual.screening.baseline > 0 && unusual.screening.deviationPercent > 25,'Screening reason includes measured deviation');
unusual = await api.saveSubmission({...unusual,price:67});
ok(unusual.status === 'verified' && !unusual.flagged,'Editing a flagged agent price reruns screening');
const sparse = await api.saveSubmission({...input,date:'2020-01-01'});
ok(sparse.status === 'pending' && sparse.flagged && sparse.screening.decision === 'insufficient-data','No historical baseline requires review');
const toReview = await api.saveSubmission({...input,price:210});
await adminLogin();
ok((await api.listSubmissions({flagged:'true',status:'pending'})).some(s => s.id === toReview.id),'Admin can filter flagged queue');
ok((await api.getAnalytics()).flagged.some(s => s.id === toReview.id),'Flagged rows appear in admin analytics');
await api.reviewSubmission({id:toReview.id,status:'rejected',reason:'Evidence does not support this price'});
await api.saveUser({...newUser,role:'user'});
await api.login({email:signup.email,password:'Reset@123'});
const demoted = await api.saveSubmission({...input,price:66});
ok(demoted.status === 'pending','Removing agent role removes auto-approval privilege');
await adminLogin(); const backup = await api.exportDatabase();
await api.importDatabase(backup); ok((await api.getDatabaseStats()).submissions === backup.submissions.length,'Backup roundtrip');
const malformed = structuredClone(backup); malformed.submissions[0].productId='missing';
await rejects(() => api.importDatabase(malformed),/no longer exists/);
const badPrice = structuredClone(backup); badPrice.submissions[0].price='20'; await rejects(() => api.importDatabase(badPrice),/must be numbers/);
ok((await api.getDatabaseStats()).submissions === backup.submissions.length,'Invalid import is atomic');
await rejects(() => api.resetDatabase('wrong'),/Type RESET/);
await api.resetDatabase('RESET BAZERLENS');
ok((await api.getSession()).id === 'admin-demo','Reset restores demo admin session');
ok(!(await api.listUsers()).some(u => u.email === signup.email),'Reset removes test account');
console.log(`PASS: ${checks} service assertions covering auth, persistence, authorization, CRUD, review, alerts, analytics and backup integrity.`);
