// <auto-generated />
using System;
using BazarLens.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BazarLens.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930010616_UpdateUserProfileFields")]
    partial class UpdateUserProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BazarLens.Server.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("activity_pkey");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "activity_user_idx")
                        .IsDescending(false, true);

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("auth_sessions_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "auth_sessions_expiry_idx");

                    b.HasIndex(new[] { "TokenHash" }, "auth_sessions_token_hash_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "auth_sessions_user_idx");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("markets_pkey");

                    b.HasIndex(new[] { "Area" }, "markets_area_idx");

                    b.HasIndex(new[] { "Name", "Area" }, "markets_name_area_unique")
                        .IsUnique();

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Area")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("area")
                        .HasDefaultValueSql("''::text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("price_alerts_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "price_alerts_user_idx")
                        .IsDescending(false, true);

                    b.ToTable("price_alerts", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.PublicCurrentPrice", b =>
                {
                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<decimal?>("Average")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("average");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("Highest")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("highest");

                    b.Property<decimal?>("Lowest")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("lowest");

                    b.Property<string>("Market")
                        .HasColumnType("text")
                        .HasColumnName("market");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Product")
                        .HasColumnType("text")
                        .HasColumnName("product");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.ToTable((string)null);

                    b.ToView("public_current_prices", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("note")
                        .HasDefaultValueSql("''::text");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date")
                        .HasColumnName("observed_on");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("quality")
                        .HasDefaultValueSql("'Not recorded'::text");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Screening")
                        .HasColumnType("jsonb")
                        .HasColumnName("screening");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("submissions_pkey");

                    b.HasIndex("MarketId");

                    b.HasIndex(new[] { "CreatedAt" }, "submissions_flagged_idx")
                        .IsDescending()
                        .HasFilter("((status = 'pending'::text) AND flagged)");

                    b.HasIndex(new[] { "CreatedAt" }, "submissions_pending_idx")
                        .IsDescending()
                        .HasFilter("(status = 'pending'::text)");

                    b.HasIndex(new[] { "ProductId", "MarketId", "Unit", "ObservedOn" }, "submissions_prices_idx")
                        .IsDescending(false, false, false, true)
                        .HasFilter("(status = 'verified'::text)");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "submissions_user_idx")
                        .IsDescending(false, true);

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.SubmissionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("reason")
                        .HasDefaultValueSql("''::text");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("source")
                        .HasDefaultValueSql("'manual'::text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("Id")
                        .HasName("submission_reviews_pkey");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "SubmissionId", "CreatedAt" }, "submission_reviews_submission_idx");

                    b.ToTable("submission_reviews", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'::text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::text");

                    b.Property<string>("Thana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thana");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.UserSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("CompactTables")
                        .HasColumnType("boolean")
                        .HasColumnName("compact_tables");

                    b.Property<string>("DefaultArea")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("default_area")
                        .HasDefaultValueSql("''::text");

                    b.Property<bool>("EmailAlerts")
                        .HasColumnType("boolean")
                        .HasColumnName("email_alerts");

                    b.Property<bool>("InAppNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("in_app_notifications");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("user_settings_pkey");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("BazarLens.Server.Models.Activity", b =>
                {
                    b.HasOne("BazarLens.Server.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("activity_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazarLens.Server.Models.AuthSession", b =>
                {
                    b.HasOne("BazarLens.Server.Models.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("auth_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazarLens.Server.Models.PriceAlert", b =>
                {
                    b.HasOne("BazarLens.Server.Models.Product", "Product")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("price_alerts_product_id_fkey");

                    b.HasOne("BazarLens.Server.Models.User", "User")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("price_alerts_user_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazarLens.Server.Models.Submission", b =>
                {
                    b.HasOne("BazarLens.Server.Models.Market", "Market")
                        .WithMany("Submissions")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("submissions_market_id_fkey");

                    b.HasOne("BazarLens.Server.Models.Product", "Product")
                        .WithMany("Submissions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("submissions_product_id_fkey");

                    b.HasOne("BazarLens.Server.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("submissions_user_id_fkey");

                    b.Navigation("Market");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazarLens.Server.Models.SubmissionReview", b =>
                {
                    b.HasOne("BazarLens.Server.Models.User", "Reviewer")
                        .WithMany("SubmissionReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("submission_reviews_reviewer_id_fkey");

                    b.HasOne("BazarLens.Server.Models.Submission", "Submission")
                        .WithMany("SubmissionReviews")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("submission_reviews_submission_id_fkey");

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("BazarLens.Server.Models.UserSetting", b =>
                {
                    b.HasOne("BazarLens.Server.Models.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("BazarLens.Server.Models.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_settings_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazarLens.Server.Models.Market", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BazarLens.Server.Models.Product", b =>
                {
                    b.Navigation("PriceAlerts");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("BazarLens.Server.Models.Submission", b =>
                {
                    b.Navigation("SubmissionReviews");
                });

            modelBuilder.Entity("BazarLens.Server.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AuthSessions");

                    b.Navigation("PriceAlerts");

                    b.Navigation("SubmissionReviews");

                    b.Navigation("Submissions");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
