import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth, useToast } from '../contexts/context';
import { mockApi } from '../services/mockApi';
import { useData } from '../components/useData';
import { Heading, Card, Field, Check, Form, DataState } from '../components/UI';
export function ProfilePage() { const {user,refresh} = useAuth(); return <><Heading title="My profile" description="Your account and community identity."/><div className="analytics-grid"><Card title="Profile details"><p className="muted">Joined {new Date(user.createdAt).toLocaleDateString()} · Role: {user.role}</p><Form key={user.id} initial={user} onSave={mockApi.updateProfile} onDone={refresh}><Field label="Display name" name="name" defaultValue={user.name} required/><Field label="Email address" name="email" type="email" defaultValue={user.email} required/><Field label="City" name="city" defaultValue={user.city} required/><Field label="Thana" name="area" defaultValue={user.area} required/><Field label="Avatar URL (optional)" name="avatarUrl" type="url" defaultValue={user.avatarUrl}/></Form></Card><Card title="Change password"><Form onSave={mockApi.changePassword} submitLabel="Change password"><Field label="Current password" name="currentPassword" type="password" required autoComplete="current-password"/><Field label="New password" name="password" type="password" minLength={8} maxLength={128} required autoComplete="new-password"/><Field label="Confirm new password" name="confirmPassword" type="password" required autoComplete="new-password"/></Form><p className="demo-warning">Use demo passwords only. This prototype stores them in browser storage.</p></Card></div></>; }
const load = async () => { const [settings,markets] = await Promise.all([mockApi.getSettings(),mockApi.listMarkets()]); return {settings,markets}; };
export function SettingsPage() { const state = useData(load), {logout,user} = useAuth(), navigate = useNavigate(), toast = useToast(); const [busy,setBusy] = useState(false); async function action(fn) { setBusy(true); try { await fn(); toast('Preferences updated.'); } catch(e) { toast(e.message,'error'); } finally { setBusy(false); } } return <><Heading title="Settings"/><DataState state={state}>{({settings,markets}) => <Card title="Your preferences"><Form key={JSON.stringify(settings)} onSave={values => mockApi.saveSettings({...settings,...values})}>{user.role !== 'agent' && <><Field label="Default area for notifications" name="defaultArea" defaultValue={settings.defaultArea} options={[{value:'',label:'All areas'},...new Set(markets.map(m => m.area))]}/><Check label="Show email previews on matching notifications (demo; no mail is sent)" name="emailAlerts" defaultChecked={settings.emailAlerts}/><Check label="Show in-app price notifications" name="inAppNotifications" defaultChecked={settings.inAppNotifications}/></>}<Check label="Use compact tables" name="compactTables" defaultChecked={settings.compactTables}/></Form><div className="action-row"><button disabled={busy} onClick={() => action(mockApi.resetSettings)}>Reset preferences</button><button disabled={busy} onClick={() => action(async () => {await logout();navigate('/login');})}>Logout</button></div></Card>}</DataState></>; }
