import { useState } from 'react';
import { useToast } from '../contexts/context';
import { api } from '../services/api';
import { useData } from '../components/useData';
import { Heading, Card, DataState, Field, Check, Form, Modal, ConfirmDialog, Table, Badge, Stats } from '../components/UI';
export function UsersPage() {
  const state = useData(api.listUsers), toast = useToast(); const [filters,setFilters] = useState({search:'',role:'',status:''}), [edit,setEdit] = useState(null), [detail,setDetail] = useState(null), [remove,setRemove] = useState(null), [busy,setBusy] = useState(false);
  async function toggle(row) { setBusy(true); try { await api.saveUser({...row,status:row.status === 'active' ? 'blocked' : 'active'}); toast('Account status updated.'); } catch(e) { toast(e.message,'error'); } finally {setBusy(false);} }
  return <><Heading title="User management" description="Add contributors and agents, and manage community accounts."><button className="dash-primary" onClick={() => setEdit({role:'user',status:'active'})}>+ Add user</button></Heading><Card><div className="filters"><Field label="Search name or email" value={filters.search} onChange={e => setFilters({...filters,search:e.target.value})}/>{['role','status'].map(key => <Field key={key} label={key === 'role' ? 'Role' : 'Status'} value={filters[key]} onChange={e => setFilters({...filters,[key]:e.target.value})} options={[{value:'',label:'All'},...(key === 'role' ? ['user','agent','admin'] : ['active','blocked'])]}/>)}<button onClick={() => setFilters({search:'',role:'',status:''})}>Clear filters</button></div><DataState state={state}>{rows => <Table rows={rows.filter(r => `${r.name} ${r.email}`.toLowerCase().includes(filters.search.toLowerCase()) && (!filters.role || r.role === filters.role) && (!filters.status || r.status === filters.status))} columns={['Name','Email','Role','Status','Contributions','Actions']} render={r => <><td>{r.name}</td><td>{r.email}</td><td>{r.role}</td><td><Badge value={r.status}/></td><td>{r.contributions}</td><td><div className="action-row"><button onClick={() => setDetail(r)}>Details</button><button onClick={() => setEdit(r)}>Edit</button><button disabled={busy} onClick={() => toggle(r)}>{r.status === 'active' ? 'Block' : 'Unblock'}</button><button onClick={() => setRemove(r)}>Delete</button></div></td></>}/>}</DataState></Card>{edit && <Modal title={edit.id ? 'Edit user' : 'Add user'} onClose={() => setEdit(null)}><Form initial={edit} onSave={api.saveUser} onDone={() => setEdit(null)}><Field label="Full name" name="name" required defaultValue={edit.name}/><Field label="Email" name="email" type="email" required defaultValue={edit.email}/><Field label="City" name="city" required defaultValue={edit.city}/><Field label="Area" name="area" required defaultValue={edit.area}/>{!edit.id && <Field label="Initial password" name="password" type="password" minLength={8} required/>}<Field label="Role" name="role" options={edit.id ? ['user','agent','admin'] : ['user','agent']} defaultValue={edit.role}/><Field label="Status" name="status" options={['active','blocked']} defaultValue={edit.status}/></Form></Modal>}{detail && <Modal title={detail.name} onClose={() => setDetail(null)}><dl className="details">{[['Email',detail.email],['Location',`${detail.area}, ${detail.city}`],['Role',detail.role],['Status',detail.status],['Joined',new Date(detail.createdAt).toLocaleDateString()],['Contributions',detail.contributions]].map(([k,v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Modal>}{remove && <ConfirmDialog title="Delete user?" message={`Delete ${remove.name}? Accounts with submission or review history must be blocked instead.`} onClose={() => setRemove(null)} onConfirm={() => api.deleteUser(remove.id)}/>}</>;
}
export function CatalogPage({kind}) {
  const product = kind === 'products'; const state = useData(product ? api.listProducts : api.listMarkets); const [search,setSearch] = useState(''), [active,setActive] = useState(''), [location,setLocation] = useState(''), [division,setDivision] = useState(''), [edit,setEdit] = useState(null), [remove,setRemove] = useState(null);
  const fields = product ? [['name','Product name'],['category','Category'],['unit','Default unit']] : [['name','Market name'],['area','Area / thana'],['district','District'],['division','Division']];
  return <><Heading title={product ? 'Products' : 'Markets'} description="Maintain the community’s shared catalog."><button className="dash-primary" onClick={() => setEdit({active:true})}>+ Add {product ? 'product' : 'market'}</button></Heading><DataState state={state}>{rows => <Card><div className="filters"><Field label="Search" value={search} onChange={e => setSearch(e.target.value)}/><Field label="State" value={active} onChange={e => setActive(e.target.value)} options={[{value:'',label:'All states'},{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}/><Field label={product ? 'Category' : 'District'} value={location} onChange={e => setLocation(e.target.value)} options={[{value:'',label:'All'},...new Set(rows.map(r => product ? r.category : r.district))]}/>{!product && <Field label="Division" value={division} onChange={e => setDivision(e.target.value)} options={[{value:'',label:'All divisions'},...new Set(rows.map(r => r.division))]}/>}<button onClick={() => {setSearch('');setActive('');setLocation('');setDivision('');}}>Clear filters</button></div><Table rows={rows.filter(r => fields.some(([k]) => r[k].toLowerCase().includes(search.toLowerCase())) && (!active || String(r.active) === active) && (!location || (product ? r.category : r.district) === location) && (!division || r.division === division))} columns={[...fields.map(([,label]) => label),'State','Actions']} render={r => <>{fields.map(([key]) => <td key={key}>{r[key]}</td>)}<td><Badge value={r.active ? 'active' : 'inactive'}/></td><td><div className="action-row"><button onClick={() => setEdit(r)}>Edit</button><button onClick={() => setRemove(r)}>Delete</button></div></td></>}/></Card>}</DataState>{edit && <Modal title={`${edit.id ? 'Edit' : 'Add'} ${product ? 'product' : 'market'}`} onClose={() => setEdit(null)}><Form initial={edit} onSave={product ? api.saveProduct : api.saveMarket} onDone={() => setEdit(null)}>{fields.map(([key,label]) => <Field key={key} label={label} name={key} defaultValue={edit[key]} required maxLength={key === 'unit' ? 20 : 120}/>)}<Check label="Active — available for new contributions" name="active" defaultChecked={edit.active}/></Form></Modal>}{remove && <ConfirmDialog title={`Delete ${remove.name}?`} message="Referenced records cannot be deleted. Edit the record and turn off Active to retire it while preserving history." onClose={() => setRemove(null)} onConfirm={() => (product ? api.deleteProduct : api.deleteMarket)(remove.id)}/>}</>;
}
export function AdminSettingsPage() {
  const state = useData(api.getDatabaseStats), toast = useToast();
  const [busy,setBusy] = useState(false);
  async function exportData() {
    setBusy(true);
    try {
      const data = await api.exportDatabase();
      const url = URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));
      const a = document.createElement('a'); a.href=url; a.download=`bazerlens-export-${new Date().toISOString().slice(0,10)}.json`; a.click();
      setTimeout(() => URL.revokeObjectURL(url),1000); toast('Database records exported.');
    } catch(e) { toast(e.message,'error'); } finally { setBusy(false); }
  }
  return <><Heading title="Admin settings" description="Live database information."/><DataState state={state}>{stats => <Stats values={Object.entries(stats)}/>}</DataState><Card title="Export records"><p>Download users, products, markets and submissions as JSON. Passwords and sessions are excluded. This report is not a database backup.</p><button className="dash-primary" disabled={busy} onClick={exportData}>{busy ? 'Exporting…' : 'Export JSON'}</button></Card><Card title="Database maintenance"><p>Backups and restores are managed through PostgreSQL. Browser demo imports and seed resets are unavailable for the live database.</p></Card></>;
}