import { useState } from 'react';
import { mockApi } from '../services/mockApi';
import { useData } from '../components/useData';
import { Heading, Card, DataState, Field, Check, Form, Modal, ConfirmDialog, Table, Badge } from '../components/UI';
import { useToast } from '../contexts/context';
const load = async () => { const [rows,products,markets] = await Promise.all([mockApi.listAlerts(),mockApi.listProducts(),mockApi.listMarkets()]); return {rows,products,markets}; };
export default function AlertsPage() {
  const state = useData(load), toast = useToast(); const [edit,setEdit] = useState(null), [remove,setRemove] = useState(null), [product,setProduct] = useState(''), [enabled,setEnabled] = useState(''), [busy,setBusy] = useState(false);
  async function toggle(row) { setBusy(true); try { await mockApi.saveAlert({...row,enabled:!row.enabled}); toast('Alert updated.'); } catch(e) { toast(e.message,'error'); } finally { setBusy(false); } }
  return <><Heading title="Price alerts" description="Keep an eye on the prices that matter to you."><button className="dash-primary" onClick={() => setEdit({enabled:true,direction:'below'})}>+ Create alert</button></Heading><DataState state={state}>{({rows,products,markets}) => <><Card><div className="filters"><Field label="Product" value={product} onChange={e => setProduct(e.target.value)} options={[{value:'',label:'All products'},...products.map(p => ({value:p.id,label:p.name}))]}/><Field label="State" value={enabled} onChange={e => setEnabled(e.target.value)} options={[{value:'',label:'All states'},{value:'true',label:'Enabled'},{value:'false',label:'Disabled'}]}/><button onClick={() => { setProduct(''); setEnabled(''); }}>Clear filters</button></div><Table rows={rows.filter(r => (!product || r.productId === product) && (!enabled || String(r.enabled) === enabled))} columns={['Product','Area','Target','State','Actions']} render={r => <><td>{r.product}</td><td>{r.area || 'All areas'}</td><td>{r.direction} ৳{r.targetPrice}/{r.unit}</td><td><Badge value={r.enabled ? 'active' : 'inactive'}/></td><td><div className="action-row"><button onClick={() => setEdit(r)}>Edit</button><button disabled={busy} onClick={() => toggle(r)}>{r.enabled ? 'Disable' : 'Enable'}</button><button onClick={() => setRemove(r)}>Delete</button></div></td></>}/></Card>{edit && <Modal title={edit.id ? 'Edit price alert' : 'Create price alert'} onClose={() => setEdit(null)}><Form initial={edit} onSave={mockApi.saveAlert} onDone={() => setEdit(null)}><Field label="Product" name="productId" defaultValue={edit.productId} options={products.filter(p => p.active || p.id === edit.productId).map(p => ({value:p.id,label:`${p.name} (${p.unit})`}))} required/><Field label="Area" name="area" defaultValue={edit.area || ''} options={[{value:'',label:'All areas'},...new Set(markets.map(m => m.area))]}/><Field label="Direction" name="direction" defaultValue={edit.direction} options={['above','below']}/><Field label="Target price (৳ per product unit)" name="targetPrice" type="number" min="0.01" step="0.01" required defaultValue={edit.targetPrice}/><Check label="Alert enabled" name="enabled" defaultChecked={edit.enabled}/></Form></Modal>}</>}</DataState>{remove && <ConfirmDialog title="Delete alert?" message={`Remove your ${remove.product} alert?`} onClose={() => setRemove(null)} onConfirm={() => mockApi.deleteAlert(remove.id)}/>}</>;
}
