import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AppLogo, Field, Check, Form, Footer } from '../components/UI';
import { useAuth, useToast } from '../contexts/context';
import { mockApi } from '../services/mockApi';
function AuthShell({title,children}) { return <div className="app-wrapper"><main className="login-container"><div className="login-card"><div className="auth-brand"><AppLogo/></div><div className="heading-section"><h1 className="main-heading">{title}</h1><p className="subtitle">Local knowledge for a fairer Bangladesh.</p></div>{children}<p className="demo-warning">Frontend demo: data and demo passwords are stored in this browser. Do not use a real password.</p></div></main><Footer/></div>; }
export function LoginPage() {
  const [email,setEmail] = useState(''), [password,setPassword] = useState(''); const {login} = useAuth(); const navigate = useNavigate(), toast = useToast();
  return <AuthShell title="Sign in to your account"><Form submitLabel="Sign in" busyLabel="Signing in…" onSave={login} onDone={user => navigate(user.role === 'admin' ? '/admin' : '/dashboard',{replace:true})}><Field label="Email address" name="email" type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="username"/><Field label="Password" name="password" type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete="current-password"/><div className="form-row"><Check label="Remember me" name="remember"/><Link to="/forgot-password">Forgot password?</Link></div></Form><p className="auth-link"><Link to="/statistics">Browse public price statistics</Link></p><div className="demo-accounts">{[['Admin','admin@bazarlens.com','Admin@123'],['User','user@bazarlens.com','User@123'],['Agent','agent@bazarlens.com','Agent@123']].map(([role,email,password]) => <div key={role}><strong>{role} demo</strong><small>{email} / {password}</small><button onClick={() => { setEmail(email); setPassword(password); }}>Fill {role} Login</button></div>)}</div><p className="muted">Existing demo database? An admin can add an Agent account or assign the Agent role under Users. Existing data is preserved.</p><button className="google-btn" onClick={() => toast('Google authentication will be connected later. Use a demo account for now.','info')}>Continue with Google</button><p className="auth-link">New to BazerLens? <Link to="/signup">Create account</Link></p></AuthShell>;
}
const signupAreas = { Dhaka: ['Dhanmondi','Tejgaon'], Chattogram: ['Kotwali'], Sylhet: ['Zindabazar'], Rajshahi: ['Boalia'], Khulna: ['Khulna Sadar'], Barishal: ['Barishal Sadar'] };
export function SignUpPage() { const [city,setCity] = useState(''); const navigate = useNavigate(), toast = useToast(); return <AuthShell title="Create your account"><Form onSave={mockApi.signup} onDone={() => { toast('Account created. Sign in with your new credentials.'); navigate('/login'); }} submitLabel="Create account"><Field label="Full name" name="name" required maxLength={120} autoComplete="name"/><Field label="Email address" name="email" type="email" required autoComplete="email"/><div className="form-grid"><Field label="City" name="city" value={city} onChange={e => setCity(e.target.value)} options={[{value:'',label:'Select a city'},...Object.keys(signupAreas)]} required/><Field label="Area" name="area" options={[{value:'',label:city ? 'Select an area' : 'Select a city first'},...(signupAreas[city] || [])]} required disabled={!city}/></div><Field label="Password (8â€“128 characters)" name="password" type="password" minLength={8} maxLength={128} required autoComplete="new-password"/><Field label="Confirm password" name="confirmPassword" type="password" required autoComplete="new-password"/><Check label="I agree to the Terms of Service and Privacy Policy" name="agreeTerms" required/><p><Link to="/terms">Read terms</Link> Â· <Link to="/privacy">Privacy policy</Link></p></Form><p className="auth-link">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>; }
export function ForgotPasswordPage() { const [account,setAccount] = useState(null), navigate = useNavigate(); return <AuthShell title="Reset demo password"><p className="demo-warning">No email will be sent. This demo allows anyone with a demo email address to reset its password.</p>{!account ? <Form onSave={mockApi.forgotPassword} onDone={setAccount} submitLabel="Find demo account"><Field label="Email address" name="email" type="email" required/></Form> : <Form initial={account} onSave={mockApi.resetPassword} onDone={() => navigate('/login')} submitLabel="Reset password"><p>Resetting {account.email}</p><Field label="New password" name="password" type="password" required minLength={8} autoComplete="new-password"/><Field label="Confirm password" name="confirmPassword" type="password" required autoComplete="new-password"/></Form>}<p className="auth-link"><Link to="/login">Back to sign in</Link></p></AuthShell>; }

