import { useState } from 'react';
import { Link } from 'react-router-dom';
import LocationFields from '../components/LocationFields';
import { emptyLocation, matchesLocation } from '../utils/locations';
import { mockApi } from '../services/mockApi';
import { useData } from '../components/useData';
import { Heading, Card, DataState, Field, Table, Stats, Bars, EmptyState, Badge } from '../components/UI';
const money = v => `৳${Number(v).toLocaleString('en-BD',{maximumFractionDigits:2})}`;
const loadCatalog = async () => { const [prices,products,markets] = await Promise.all([mockApi.getPrices(),mockApi.listProducts(),mockApi.listMarkets()]); return {prices,products,markets}; };
export function PricesPage() {
  const state = useData(loadCatalog);
  return <><Heading title="Bazar prices" description="Browse the latest verified product prices."><Link className="dash-primary" to="/submissions?create=1">+ Contribute Price</Link></Heading><DataState state={state}>{data => <PriceExplorer data={data}/>}</DataState></>;
}
function PriceExplorer({data}) {
  const {prices,products,markets} = data;
  const [location,setLocation] = useState({...emptyLocation});
  const marketIds = new Set(markets.filter(m => matchesLocation(m,location)).map(m => m.id));
  const [filters,setFilters] = useState({}), [sort,setSort] = useState('name');
  const set = (key,value) => setFilters(f => ({...f,[key]:value}));
  const groups = new Map();
  prices.filter(row => marketIds.has(row.marketId)).forEach(row => {
    const key = row.productId + ':' + row.unit;
    const group = groups.get(key) || {...row,id:key,sum:0,count:0};
    group.sum += row.average; group.count++;
    if (row.date > group.date) group.date = row.date;
    groups.set(key,group);
  });
  const rows = [...groups.values()].map(r => ({...r,average:r.sum/r.count})).filter(r => Object.entries(filters).every(([k,v]) => !v || (k === 'search' ? r.product.toLowerCase().includes(v.toLowerCase()) : r[k] === v))).sort((a,b) => sort === 'price' ? a.average-b.average : sort === 'price-desc' ? b.average-a.average : sort === 'date' ? b.date.localeCompare(a.date) : a.product.localeCompare(b.product));
  return <Card><div className="filters"><LocationFields markets={markets} value={location} onChange={setLocation}/></div><div className="filters"><Field label="Search products" value={filters.search || ''} onChange={e => set('search',e.target.value)}/>{[['productId','Product',products.map(p => ({value:p.id,label:p.name}))],['category','Category',[...new Set(products.map(p => p.category))]]].map(([key,label,options]) => <Field key={key} label={label} value={filters[key] || ''} onChange={e => set(key,e.target.value)} options={[{value:'',label:'All'},...options]}/>)}<Field label="Sort by" value={sort} onChange={e => setSort(e.target.value)} options={[{value:'name',label:'Product name'},{value:'price',label:'Price: ascending'},{value:'price-desc',label:'Price: descending'},{value:'date',label:'Most recent'}]}/><button onClick={() => {setFilters({});setSort('name');setLocation({...emptyLocation});}}>Clear filters</button></div><Table rows={rows} columns={['Product','Category','Average price','Unit','Updated']} render={r => <><td><strong>{r.product}</strong></td><td>{r.category}</td><td>{money(r.average)}</td><td>{r.unit}</td><td>{r.date}</td></>}/><p className="muted">Each product price averages the latest verified average from each bazar in the selected location. Updated shows the most recent observation. Demo prices are illustrative.</p></Card>;
}
const loadDashboard = async () => { const [summary,settings] = await Promise.all([mockApi.getSummary(),mockApi.getSettings()]); return {summary,settings}; };
export function DashboardPage({admin = false}) { const state = useData(loadDashboard); return <><Heading title={admin ? 'Administration overview' : 'Dashboard'} description={admin ? 'The community, the contributions, and what needs your attention.' : 'Daily bazar prices from real people, across Bangladesh.'}><Link className="dash-primary" to={admin ? '/admin/submissions' : '/submissions?create=1'}>{admin ? 'Review submissions' : '+ Contribute Price'}</Link></Heading><DataState state={state}>{data => <DashboardContent {...data} admin={admin}/>}</DataState>{admin && <AdminActivity/>}</>; }
function AdminActivity() { const state = useData(mockApi.getAnalytics); return <DataState state={state}>{data => <div className="analytics-grid"><Card title="Submissions by month"><Bars rows={data.byMonth}/></Card><Card title="Recent administration activity"><ul className="activity-list">{data.activity.slice(0,5).map(a => <li key={a.id}><span>{a.message}</span><time>{new Date(a.createdAt).toLocaleString()}</time></li>)}</ul></Card></div>}</DataState>; }
function DashboardContent({summary:s,settings,admin}) {
  const [search,setSearch] = useState(''), [area,setArea] = useState(settings.defaultArea);
  const rice = s.prices.filter(p => p.productId === 'p0'); const avg = rice.length ? rice.reduce((a,p) => a+p.average,0)/rice.length : 0;
  const values = admin ? [['Total users',s.users],['Active / blocked',`${s.activeUsers} / ${s.blockedUsers}`],['Total submissions',s.total],['Pending review',s.pending],['Verified',s.verified],['Rejected',s.rejected],['Products',s.products],['Markets',s.markets]] : [['My submissions',s.total],['Average rice / kg',rice.length ? money(avg) : 'No data'],['Pending',s.pending],['Verified',s.verified]];
  return <><Stats values={values}/>{admin && <div className="action-row"><Link to="/admin/users">Manage users</Link><Link to="/admin/submissions">Review pending prices</Link><Link to="/admin/analytics">View activity and analytics</Link></div>}<div className="dash-charts"><Card title="Average rice price by area"><Bars rows={rice.map(p => ({label:p.area,value:p.average}))}/></Card><Card title="Market areas in Bangladesh"><MarketMap prices={rice}/></Card></div><Card><div className="filters"><Field label="Search recent submissions" value={search} onChange={e => setSearch(e.target.value)}/><Field label="Area" value={area} onChange={e => setArea(e.target.value)} options={[{value:'',label:'All areas'},...new Set(s.prices.map(p => p.area))]}/><button onClick={() => {setSearch('');setArea('');}}>Clear filters</button></div></Card><div className="dash-bottom-grid"><Card title="Recent price submissions"><Table rows={s.recent.filter(r => r.product.toLowerCase().includes(search.toLowerCase()) && (!area || r.area === area))} columns={['Product','Price','Area','Date','Status']} render={r => <><td>{r.product}</td><td>{money(r.price)}/{r.unit}</td><td>{r.area}</td><td>{r.date}</td><td><Badge value={r.status}/></td></>}/><Link to={admin ? '/admin/submissions' : '/submissions'}>View all submissions</Link></Card><Card title="Price alerts & notifications">{s.notifications.length ? s.notifications.slice(0,4).map(n => <article className="notification" key={n.id}><p>{n.message}</p>{n.emailPreview && <small>Email preview · no email sent</small>}</article>) : <EmptyState message="No price alert matches right now."/>}<Link to="/alerts">Manage alerts</Link></Card></div></>;
}
function MarketMap({prices}) { const positions = [[149,148],[120,164],[220,235],[226,87],[68,109],[87,211],[147,240]]; return <><svg className="market-map" viewBox="0 0 310 292" role="img" aria-label="Illustrative Bangladesh map with verified rice prices"><path d="m81 18 28 19 20-5 16 23 30-6 12 16 40-6 25 27-21 26-24-1-16 24 3 23 24 17 6 38 22 43-16-9-18-27-17 4-11-20-18 15-13-9-10 18-17-22-7-28-21-12 7-30-19-20 13-26-16-19 9-17-14-23Z" fill="#b6e4b9" stroke="#8bcf9e" strokeWidth="2"/><path d="m109 37 6 47 31 22-5 42 19 34-13 47M69 110l46-26 63 13 43-18M64 171l77-23 52-16M94 221l47-36 43 24" stroke="#dff3df" strokeWidth="3" fill="none"/>{prices.filter(p => /^m[0-6]$/.test(p.marketId)).map(p => {const [x,y]=positions[Number(p.marketId.slice(1))]; return <g key={p.id}><circle cx={x} cy={y} r="7" fill="#059669" stroke="white" strokeWidth="2"><title>{`${p.market}, ${p.area}: ${money(p.average)}/kg`}</title></circle><text x={x+8} y={y-7}>{money(p.average)}</text></g>;})}</svg><p className="muted">Illustrative seed-market locations · hover a marker for details.</p></>; }
export function AnalyticsPage({admin = false}) { const state = useData(mockApi.getAnalytics); return <><Heading title={admin ? 'Community analytics' : 'My contribution analytics'}/><DataState state={state}>{d => <><Stats values={[[admin ? 'Total submissions' : 'Total contributions',d.total],['Verified rate',`${d.verifiedRate}%`],['Pending',d.pending],['Rejected',d.rejected.length],...(admin ? [['Flagged for review',d.flagged.length]] : [])]}/><div className="analytics-grid">{[['Submissions by status',d.byStatus],['Most submitted products',d.byProduct],['Contributions by area',d.byArea],['Contributions by month',d.byMonth],...(admin ? [['User growth by join month',d.userGrowth],['Most active contributors',d.contributors]] : [])].map(([title,rows]) => <Card title={title} key={title}><Bars rows={rows}/></Card>)}</div>{admin && <><Card title="Current average prices by market"><Table rows={d.prices} columns={['Product','Market','Average','Unit']} render={r => <><td>{r.product}</td><td>{r.market}</td><td>{money(r.average)}</td><td>{r.unit}</td></>}/></Card><Card title="Flagged / rejected price summary"><Table rows={[...d.flagged,...d.rejected]} columns={['Product','Price','Area','Reason']} render={r => <><td>{r.product}</td><td>{money(r.price)}/{r.unit}</td><td>{r.area}</td><td className="wrap-cell">{r.rejectionReason || r.screening?.reason}</td></>}/></Card></>}<Card title="Recent activity">{d.activity.length ? <ul className="activity-list">{d.activity.map(a => <li key={a.id}><span>{a.message}</span><time>{new Date(a.createdAt).toLocaleString()}</time></li>)}</ul> : <EmptyState message="Your activity will appear here."/>}</Card></>}</DataState></>; }
