import { Link } from 'react-router-dom';
import { AppLogo, Footer } from '../components/UI';
const content = {
  about: ['About BazerLens', ['Community market prices','Contributors record observed prices in Bangladesh markets. Verified reports power price comparisons and public statistics.'],['How prices work','Compare products using the same unit and market. Prices are averages of verified reports on the latest observation date for each product and market. Sellers may charge different prices.']],
  privacy: ['Privacy Policy', ['Account data','Account details, submissions, alerts and preferences are stored by the backend in the application database. Passwords are hashed. Sign-in uses an HTTP-only session cookie.'],['Your choices','Edit your profile and pending submissions, delete alerts, or reset preferences from your account. Contact your administrator for account deletion.'],['External resources','Avatar images and evidence links may contact external websites. Email delivery and password recovery are currently unavailable.']],
  terms: ['Terms of Service', ['Community contributions','Submit accurate observations with the correct product, unit, market and date. Administrators may reject reports and block abusive accounts. Reviewed submissions remain read-only.'],['Price information','Prices are community observations, not offers or guaranteed seller prices. Verify prices before buying.']],
  help: ['Help Center', ['Your account','Create an account or sign in with your registered email and password. Administrators can add contributors and agents through User management.'],['Contribute a price','Select an active category, product, quality and market, then enter a positive price and observation date. Pending submissions can be edited or deleted.'],['Reviews and alerts','Agent prices within 25% of a recent market median are automatically verified when at least three independently verified observation days exist in the preceding 30 days. Other reports go to administrator review. In-app alerts compare verified prices with your saved targets.'],['Sessions','Remember me keeps your session for up to 30 days. Other sessions expire after one day and use a browser session cookie. Logout revokes the session.'],['Troubleshooting','Clear filters if a table is empty. Inactive products and markets are unavailable for new reports. Contact your administrator if the API cannot be reached or you cannot sign in.']],
};
export function PublicPage({page}) { const [title,...sections] = content[page]; return <div className="public-page"><header className="public-header"><Link to="/"><AppLogo/></Link><Link to="/">Open BazerLens</Link></header><main><h1>{title}</h1>{sections.map(([heading,text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<div className="action-row"><Link className="dash-primary" to="/">Go to dashboard / sign in</Link><Link to="/login">Login</Link></div></main><Footer/></div>; }
export function ErrorPage({denied = false}) { return <div className="public-page"><main><div className="auth-brand"><AppLogo/></div><h1>{denied ? 'Access denied' : 'Page not found'}</h1><p>{denied ? 'Your current account does not have permission to open this page.' : 'The address does not match a BazerLens page.'}</p><Link className="dash-primary" to="/">Return to BazerLens</Link></main><Footer/></div>; }
