import { Link } from 'react-router-dom';
import { AppLogo, Footer } from '../components/UI';
const content = {
  about: ['About BazerLens', ['People’s data for fairer prices','BazerLens is a community bazar-price prototype for Bangladesh. Contributors record observed prices at local markets, and agents can submit prices for automatic screening. Normal agent prices are approved automatically; unusual prices and general-user contributions go to administrators for review.'],['How prices work','Compare products using the same unit and market. Current prices summarize verified observations on the most recent available day; trends summarize verified daily observations. Market prices vary by quality, size, season and location.'],['A frontend demonstration','All accounts and prices on this version are examples saved in your browser. They are not live market quotes.']],
  privacy: ['Privacy Policy', ['Local demo storage','This prototype stores your name, email, location, preferences, submissions, alerts, and demo password in localStorage. Remembered sessions use localStorage; other sessions use sessionStorage. No backend account service receives these records.'],['Your choices','You can edit your profile and pending submissions, delete alerts, and reset preferences. Administrators can export or reset the demo database. Clearing this site’s browser storage removes its local data. Backups contain demo passwords.'],['External resources','Opening evidence links or loading an avatar URL contacts the external website. Do not submit private documents, personal evidence, or real passwords. Google sign-in and email delivery are not connected.'],['Production policy','A real deployment needs a published operator contact, retention schedule, lawful processing basis, and secure account and deletion procedures before accepting personal data.']],
  terms: ['Terms of Service', ['Use the demo responsibly','Use fictional credentials and submit honest example observations. Do not upload sensitive information or link to unlawful or harmful content.'],['Community contributions','Record the product’s specified unit, market, observation date and price. Administrators may reject incomplete or inconsistent entries and block abusive demo accounts. Reviewed submissions remain read-only to preserve their history.'],['No price guarantee','All seeded data is illustrative. Prices are not offers, official statistics, or a guarantee that a market will sell at the displayed value. Verify prices with sellers before buying.'],['Availability','Browser storage can be cleared or modified. This prototype provides no durability or security guarantee. Exported backups are for demo testing only.']],
  help: ['Help Center', ['Try an account','Use Fill User Login to explore prices, create contributions and set alerts. Use Fill Admin Login to review submissions and manage the catalog. Use Fill Agent Login on a fresh database to try automatic screening. All three demo credentials appear on the sign-in page. Existing databases keep their data: an administrator can assign the Agent role under Users.'],['Contribute a price','Open Submissions, select Contribute Price, choose an active product and market, then enter a positive price and an observation date no later than today. Area and unit come from the catalog. Pending submissions can be edited or deleted.'],['Reviews and alerts','Agent prices within 25% of a recent same-market median are automatically verified when at least 3 independent verified observation days exist in the last 30 days. Unusual prices and insufficient baselines are flagged for administrator review. General-user submissions remain pending. Administrators approve or reject pending prices. Rejection reasons appear in submission details. Alerts compare the latest verified market average with your target; matching alerts appear under Notifications. Email previews never send mail.'],['Sessions and storage','Remember me keeps the session across browser restarts. Without it, the session stays in the current tab’s session storage. Refresh preserves both session types. Logout clears both. Password reset is a local demo and sends no email.'],['Troubleshooting','Clear filters if a table is empty. Inactive products and markets are unavailable for new contributions. If storage is unavailable, enable it for this site. The administrator can import a valid backup or reset the database.']],
};
export function PublicPage({page}) { const [title,...sections] = content[page]; return <div className="public-page"><header className="public-header"><Link to="/"><AppLogo/></Link><Link to="/">Open BazerLens</Link></header><main><h1>{title}</h1>{sections.map(([heading,text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<div className="action-row"><Link className="dash-primary" to="/">Go to dashboard / sign in</Link><Link to="/login">Login</Link></div></main><Footer/></div>; }
export function ErrorPage({denied = false}) { return <div className="public-page"><main><div className="auth-brand"><AppLogo/></div><h1>{denied ? 'Access denied' : 'Page not found'}</h1><p>{denied ? 'This page requires an administrator account. Your current account does not have permission.' : 'The address does not match a BazerLens page.'}</p><Link className="dash-primary" to="/">Return to BazerLens</Link></main><Footer/></div>; }
