import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { useData } from '../components/useData';
import LocationFields from '../components/LocationFields';
import { locationForMarket } from '../utils/locations';
import { qualityOptions } from '../data/submissionOptions';
import { today } from '../utils/validation';
import { Heading, Card, DataState, Field, Form, Modal, ConfirmDialog, Table, Badge } from '../components/UI';
const load = async () => { const [rows,products,markets] = await Promise.all([api.listSubmissions(),api.listProducts(),api.listMarkets()]); return {rows,products,markets}; };
export function SubmissionForm({ row = {}, products, markets, onClose }) {
  const [productId,setProduct] = useState(row.productId || products.find(p => p.active)?.id || '');
  const [category,setCategory] = useState(products.find(p => p.id === productId)?.category || '');
  const availableProducts = products.filter(p => p.active || p.id === row.productId);
  const categoryProducts = availableProducts.filter(p => p.category === category);
  function changeCategory(value) { setCategory(value); setProduct(availableProducts.find(p => p.category === value)?.id || ''); }
  const product = products.find(p => p.id === productId);
  const [location,setLocation] = useState(() => locationForMarket(markets.find(m => m.id === row.marketId)));
  const availableMarkets = markets.filter(m => m.active || m.id === row.marketId);
  return <Modal title={row.id ? 'Edit pending submission' : 'Contribute a Price'} onClose={onClose}><p>Agent prices within 25% of a recent market median are automatically verified. Unusual prices or insufficient comparison data go to admin review. General-user submissions require review.</p><Form initial={row} onSave={api.saveSubmission} onDone={onClose} submitLabel="Submit price"><Field label="Category" name="category" value={category} onChange={e => changeCategory(e.target.value)} options={[...new Set(availableProducts.map(p => p.category))]} required/><Field label="Product" name="productId" value={productId} onChange={e => setProduct(e.target.value)} options={categoryProducts.map(p => ({value:p.id,label:p.name}))} required/><Field label="Quality" name="quality" options={[{value:'',label:'Select quality'},...qualityOptions]} defaultValue={row.quality || ''} required/><div className="form-grid"><Field label="Price (৳)" name="price" type="number" min="0.01" max="1000000" step="0.01" required defaultValue={row.price}/><Field label="Unit" name="unit" value={product?.unit || ''} readOnly required/></div><div className="form-grid"><LocationFields markets={availableMarkets} value={location} onChange={setLocation} required/></div>{!availableMarkets.length && <p role="status">No bazars are available yet. Ask an administrator to add a market.</p>}<Field label="Observed date" name="date" type="date" defaultValue={row.date || today()} max={today()} required/><Field label="Note (optional)" name="note" defaultValue={row.note} maxLength={1000}/><Field label="Evidence URL (optional)" name="evidenceUrl" type="url" defaultValue={row.evidenceUrl}/></Form></Modal>;
}
export default function SubmissionsPage({admin = false, flaggedOnly = false}) {
  const state = useData(load); const [params,setParams] = useSearchParams(); const [filters,setFilters] = useState({}), [edit,setEdit] = useState(null), [remove,setRemove] = useState(null), [review,setReview] = useState(null);
  const set = (key,value) => setFilters(f => ({...f,[key]:value}));
  const close = () => { setEdit(null); setParams({}, {replace:true}); };
  return <><Heading title={flaggedOnly ? 'Product review' : admin ? 'Submission review' : 'My submissions'} description={flaggedOnly ? 'Flagged prices awaiting a decision. Approved and rejected items leave this queue.' : admin ? 'Verify community prices and keep the data trustworthy.' : 'Every contribution makes the bazar more transparent.'}>{!admin && <button className="dash-primary" onClick={() => setEdit({})}>+ Contribute Price</button>}</Heading><DataState state={state}>{({rows,products,markets}) => {
    const filtered = rows.filter(r => (!flaggedOnly || r.flagged && r.status === 'pending') && Object.entries(filters).every(([k,v]) => !v || (k === 'search' ? `${r.product} ${r.market} ${r.note}`.toLowerCase().includes(v.toLowerCase()) : String(r[k]) === v)));
    return <><Card><div className="filters"><Field label="Search" value={filters.search || ''} onChange={e => set('search',e.target.value)}/>{!flaggedOnly && <Field label="Status" value={filters.status || ''} onChange={e => set('status',e.target.value)} options={[{value:'',label:'All statuses'},'pending','verified','rejected']}/>}<Field label="Product" value={filters.productId || ''} onChange={e => set('productId',e.target.value)} options={[{value:'',label:'All products'},...products.map(p => ({value:p.id,label:p.name}))]}/><Field label="Date" type="date" value={filters.date || ''} onChange={e => set('date',e.target.value)}/>{admin && <>{!flaggedOnly && <Field label="Screening" value={filters.flagged || ''} onChange={e => set('flagged',e.target.value)} options={[{value:'',label:'All submissions'},{value:'true',label:'Flagged for review'}]}/>}<Field label="Contributor" value={filters.userId || ''} onChange={e => set('userId',e.target.value)} options={[{value:'',label:'All contributors'},...Array.from(new Map(rows.map(r => [r.userId,{value:r.userId,label:r.user}])).values())]}/><Field label="Market" value={filters.marketId || ''} onChange={e => set('marketId',e.target.value)} options={[{value:'',label:'All markets'},...markets.map(m => ({value:m.id,label:m.name}))]}/><Field label="Area" value={filters.area || ''} onChange={e => set('area',e.target.value)} options={[{value:'',label:'All areas'},...new Set(rows.map(r => r.area))]}/></>}<button onClick={() => setFilters({})}>Clear filters</button></div><Table rows={filtered} columns={['Product','Category','Quality','Price','Market / area','Date',...(admin ? ['Contributor'] : []),'Status','Actions']} render={r => <><td>{r.product}</td><td>{r.category}</td><td>{r.quality || 'Not recorded'}</td><td>৳{r.price} / {r.unit}</td><td>{r.market}<small className="cell-small">{r.area}</small></td><td>{r.date}</td>{admin && <td>{r.user}</td>}<td><Badge value={r.status}/>{r.flagged && <small className="cell-small">Flagged: {r.screening?.decision}</small>}{r.screening?.decision === 'auto-approved' && <small className="cell-small">Automatically approved</small>}</td><td><div className="action-row">{r.status === 'pending' && (admin ? <><button onClick={() => setReview({...r,next:'verified'})}>Approve</button><button onClick={() => setReview({...r,next:'rejected'})}>Reject</button></> : <><button onClick={() => setEdit(r)}>Edit</button><button onClick={() => setRemove(r)}>Delete</button></>)}</div><p className="submission-note">{r.rejectionReason || r.screening?.reason || (r.status === 'pending' ? 'Awaiting review' : 'Reviewed')}</p>{r.note && <p className="submission-note">{r.note}</p>}{r.evidenceUrl && <a href={r.evidenceUrl} target="_blank" rel="noreferrer">Evidence</a>}</td></>}/></Card>{(edit || (!admin && params.has('create'))) && <SubmissionForm row={edit || {}} products={products} markets={markets} onClose={close}/>}</>;
  }}</DataState>{remove && <ConfirmDialog title="Delete pending submission?" message={`Remove your ${remove.product} price? This cannot be undone.`} onClose={() => setRemove(null)} onConfirm={() => api.deleteSubmission(remove.id)}/>}{review && <Modal title={review.next === 'verified' ? 'Approve this price?' : 'Reject this price?'} onClose={() => setReview(null)}><p className="demo-warning">{review.screening?.reason || 'Legacy submission ? check price and evidence manually.'}</p><p>{review.product}: ৳{review.price}/{review.unit} at {review.market}</p><Form onSave={values => api.reviewSubmission({id:review.id,status:review.next,reason:values.reason})} onDone={() => setReview(null)} submitLabel="Confirm review">{review.next === 'rejected' ? <Field label="Rejection reason" name="reason" required maxLength={1000}/> : <p>Approval includes this price in public price comparisons.</p>}</Form></Modal>}</>;
}
