import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { mockApi } from '../services/mockApi';
import { useData } from '../components/useData';
import { today } from '../utils/validation';
import { Heading, Card, DataState, Field, Form, Modal, ConfirmDialog, Table, Badge } from '../components/UI';
const load = async () => { const [rows,products,markets] = await Promise.all([mockApi.listSubmissions(),mockApi.listProducts(),mockApi.listMarkets()]); return {rows,products,markets}; };
export function SubmissionForm({ row = {}, products, markets, onClose }) {
  const [productId,setProduct] = useState(row.productId || products.find(p => p.active)?.id || ''), [marketId,setMarket] = useState(row.marketId || markets.find(m => m.active)?.id || '');
  const product = products.find(p => p.id === productId), market = markets.find(m => m.id === marketId);
  return <Modal title={row.id ? 'Edit pending submission' : 'Contribute a Price'} onClose={onClose}><p>Agent prices within 25% of a recent market median are automatically verified. Unusual prices or insufficient comparison data go to admin review. General-user submissions require review.</p><Form initial={row} onSave={mockApi.saveSubmission} onDone={onClose} submitLabel="Submit price"><Field label="Product" name="productId" value={productId} onChange={e => setProduct(e.target.value)} options={products.filter(p => p.active || p.id === row.productId).map(p => ({value:p.id,label:p.name}))} required/><div className="form-grid"><Field label="Price (৳)" name="price" type="number" min="0.01" max="1000000" step="0.01" required defaultValue={row.price}/><Field label="Unit" name="unit" value={product?.unit || ''} readOnly required/></div><Field label="Market" name="marketId" value={marketId} onChange={e => setMarket(e.target.value)} options={markets.filter(m => m.active || m.id === row.marketId).map(m => ({value:m.id,label:`${m.name} — ${m.area}`}))} required/><Field label="Area" value={market?.area || ''} readOnly/><Field label="Observed date" name="date" type="date" defaultValue={row.date || today()} max={today()} required/><Field label="Note (optional)" name="note" defaultValue={row.note} maxLength={1000}/><Field label="Evidence URL (optional)" name="evidenceUrl" type="url" defaultValue={row.evidenceUrl}/></Form></Modal>;
}
export default function SubmissionsPage({admin = false}) {
  const state = useData(load); const [params,setParams] = useSearchParams(); const [filters,setFilters] = useState({}), [edit,setEdit] = useState(null), [detail,setDetail] = useState(null), [remove,setRemove] = useState(null), [review,setReview] = useState(null);
  const set = (key,value) => setFilters(f => ({...f,[key]:value}));
  const close = () => { setEdit(null); setParams({}, {replace:true}); };
  return <><Heading title={admin ? 'Submission review' : 'My submissions'} description={admin ? 'Verify community prices and keep the data trustworthy.' : 'Every contribution makes the bazar more transparent.'}>{!admin && <button className="dash-primary" onClick={() => setEdit({})}>+ Contribute Price</button>}</Heading><DataState state={state}>{({rows,products,markets}) => {
    const filtered = rows.filter(r => Object.entries(filters).every(([k,v]) => !v || (k === 'search' ? `${r.product} ${r.market} ${r.note}`.toLowerCase().includes(v.toLowerCase()) : String(r[k]) === v)));
    return <><Card><div className="filters"><Field label="Search" value={filters.search || ''} onChange={e => set('search',e.target.value)}/><Field label="Status" value={filters.status || ''} onChange={e => set('status',e.target.value)} options={[{value:'',label:'All statuses'},'pending','verified','rejected']}/><Field label="Product" value={filters.productId || ''} onChange={e => set('productId',e.target.value)} options={[{value:'',label:'All products'},...products.map(p => ({value:p.id,label:p.name}))]}/><Field label="Date" type="date" value={filters.date || ''} onChange={e => set('date',e.target.value)}/>{admin && <><Field label="Screening" value={filters.flagged || ''} onChange={e => set('flagged',e.target.value)} options={[{value:'',label:'All submissions'},{value:'true',label:'Flagged for review'}]}/><Field label="Contributor" value={filters.userId || ''} onChange={e => set('userId',e.target.value)} options={[{value:'',label:'All contributors'},...Array.from(new Map(rows.map(r => [r.userId,{value:r.userId,label:r.user}])).values())]}/><Field label="Market" value={filters.marketId || ''} onChange={e => set('marketId',e.target.value)} options={[{value:'',label:'All markets'},...markets.map(m => ({value:m.id,label:m.name}))]}/><Field label="Area" value={filters.area || ''} onChange={e => set('area',e.target.value)} options={[{value:'',label:'All areas'},...new Set(rows.map(r => r.area))]}/></>}<button onClick={() => setFilters({})}>Clear filters</button></div><Table rows={filtered} columns={['Product','Price','Market / area','Date',...(admin ? ['Contributor'] : []),'Status','Actions']} render={r => <><td>{r.product}</td><td>৳{r.price} / {r.unit}</td><td>{r.market}<small className="cell-small">{r.area}</small></td><td>{r.date}</td>{admin && <td>{r.user}</td>}<td><Badge value={r.status}/>{r.flagged && <small className="cell-small">Flagged: {r.screening?.decision}</small>}{r.screening?.decision === 'auto-approved' && <small className="cell-small">Automatically approved</small>}</td><td><div className="action-row"><button onClick={() => setDetail(r)}>Details</button>{r.status === 'pending' && (admin ? <><button onClick={() => setReview({...r,next:'verified'})}>Approve</button><button onClick={() => setReview({...r,next:'rejected'})}>Reject</button></> : <><button onClick={() => setEdit(r)}>Edit</button><button onClick={() => setRemove(r)}>Delete</button></>)}</div></td></>}/></Card>{(edit || (!admin && params.has('create'))) && <SubmissionForm row={edit || {}} products={products} markets={markets} onClose={close}/>}</>;
  }}</DataState>{detail && <Modal title={`${detail.product} submission`} onClose={() => setDetail(null)}><dl className="details">{[['Price',`৳${detail.price}/${detail.unit}`],['Market',detail.market],['Area',detail.area],['Date',detail.date],['Contributor',detail.user],['Status',detail.status],['Screening',detail.screening?.reason || 'Legacy submission ? manual review'],['Decision',detail.screening?.decision || 'manual'],['Note',detail.note || 'No note'],['Rejection reason',detail.rejectionReason || 'None']].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{detail.evidenceUrl && <a href={detail.evidenceUrl} target="_blank" rel="noreferrer">Open evidence</a>}<h3>Review history</h3>{detail.history.length ? detail.history.map((h,i) => <p key={i}>{h.status} · {new Date(h.at).toLocaleString()} · {h.source === 'automatic' ? 'Automatic price screening' : h.reviewerId} {h.reason}</p>) : <p>Awaiting administrator review.</p>}</Modal>}{remove && <ConfirmDialog title="Delete pending submission?" message={`Remove your ${remove.product} price? This cannot be undone.`} onClose={() => setRemove(null)} onConfirm={() => mockApi.deleteSubmission(remove.id)}/>}{review && <Modal title={review.next === 'verified' ? 'Approve this price?' : 'Reject this price?'} onClose={() => setReview(null)}><p className="demo-warning">{review.screening?.reason || 'Legacy submission ? check price and evidence manually.'}</p><p>{review.product}: ৳{review.price}/{review.unit} at {review.market}</p><Form onSave={values => mockApi.reviewSubmission({id:review.id,status:review.next,reason:values.reason})} onDone={() => setReview(null)} submitLabel="Confirm review">{review.next === 'rejected' ? <Field label="Rejection reason" name="reason" required maxLength={1000}/> : <p>Approval includes this price in public comparisons and trends.</p>}</Form></Modal>}</>;
}
